// <auto-generated />
using System;
using BillsManagement.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BillsManagement.DAL.Migrations
{
    [DbContext(typeof(BillsManagementContext))]
    [Migration("20210716173414_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BillsManagement.DAL.Models.Authentication", b =>
                {
                    b.Property<Guid>("AuthenticationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuthenticationId");

                    b.HasIndex("UserId");

                    b.ToTable("Authentication");
                });

            modelBuilder.Entity("BillsManagement.DAL.Models.Charge", b =>
                {
                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("date");

                    b.Property<string>("BillName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BillStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal?>("DueAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BillId")
                        .HasName("PK__Bills__11F2FC6A4C54C5F0");

                    b.HasIndex("UserId");

                    b.ToTable("Charges");
                });

            modelBuilder.Entity("BillsManagement.DAL.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Phone")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BillsManagement.DAL.Models.Authentication", b =>
                {
                    b.HasOne("BillsManagement.DAL.Models.User", "User")
                        .WithMany("Authentications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UsersAuthentication")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillsManagement.DAL.Models.Charge", b =>
                {
                    b.HasOne("BillsManagement.DAL.Models.User", "User")
                        .WithMany("Charges")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UsersBills")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BillsManagement.DAL.Models.User", b =>
                {
                    b.Navigation("Authentications");

                    b.Navigation("Charges");
                });
#pragma warning restore 612, 618
        }
    }
}
